### DISCUSSION TITLE
CasaOS Docker Compose Template for aarch64

### DISCUSSION THREAD

**Discussion by hqnicolas** [xtekky/gpt4free#2650] [Show and tell]
If you're trying to run it on CasaOS ARM64

```
name: loving_renaud
services:
  g4f:
    cpu_shares: 90
    command:
      - python -m g4f --debug
    container_name: continue4free
    deploy:
      resources:
        limits:
          memory: 3919M
    entrypoint:
      - /bin/sh
      - -c
    hostname: continue4free
    image: hlohaus789/g4f:latest-slim
    labels:
      icon: https://icon.casaos.io/main/all/g4f.png
    ports:
      - target: 1337
        published: "1337"
        protocol: tcp
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - type: bind
        source: /DATA/AppData/har_and_cookies
        target: /app/har_and_cookies
      - type: bind
        source: /DATA/AppData/generated_images
        target: /app/generated_images
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/g4f.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: loving_renaud
  title:
    custom: Continue4free
    en_us: g4f
```
