### ISSUE TITLE
HTML content response when using GPT-4 from Liaobots

### ISSUE THREAD

**Issue by Type-32** [xtekky/gpt4free#1090]
**Bug description**
Asked a question using the Liaobots provider with gpt-4 model
Does not answer question, but instead spouts out an html content

ex.
1. Select gpt-4 and Liaobots provider
2. Write anything in your prompt
3. See error

**Screenshots**
<img width="712" alt="Screenshot 2023-10-17 at 07 16 41" src="https://github.com/xtekky/gpt4free/assets/87076491/92ec016b-edc7-4de1-85a2-f62808e62339">
<img width="872" alt="Screenshot 2023-10-17 at 07 15 40" src="https://github.com/xtekky/gpt4free/assets/87076491/5848e95a-53bc-4898-a8dd-2f0f14928cbc">

**Environment**
- Deployed using Portainer Stack
- location: China

**Additional context**
docker-compose.yml
```yml
version: '3'

services:
  gpt4free-api: &gpt4free
    image: gpt4free:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    command: api
  gpt4free-gui:
    <<: *gpt4free
    ports:
      - '20002:80'
    command: gui
```
