### ISSUE TITLE
Stream System

### ISSUE THREAD

**Issue by mazinn444** [xtekky/gpt4free#2300]
**Bug description**

The Streaming system doesn't work very well. Therefore, I would like you to fix this bug.

Like, if you try to run a:

```python
for chunk in g4f.ChatCompletion(
     model="gpt-4o",
     messages=[{'role': 'user', 'content': 'Example'}],
     stream=True
):
     print(chunk, end='', flush=True)
```
just returns the entire response at once, no chunk by chunk

**Environment**
- Python 3.13.

**Comment by kqlio67** [comment]
Hi @mazinn444,

_I noticed you might be using an outdated method for streaming. The documentation has been updated with the correct way to implement streaming. **Here are two examples that should help you get it working properly:**_


**Using regular client:**
**Documentation:** https://github.com/xtekky/gpt4free/blob/main/docs/client.md#streaming-completions
```python
from g4f.client import Client

client = Client()

stream = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "user",
            "content": "Say this is a test"
        }
    ],
    stream=True,
)

for chunk in stream:
    if chunk.choices[0].delta.content:
        print(chunk.choices[0].delta.content or "", end="")
```

**Using async client:**
**Documentation:** https://github.com/xtekky/gpt4free/blob/main/docs/async_client.md#streaming-completions
```python
import asyncio
from g4f.client import Client

async def main():
    client = Client()
    
    stream = await client.chat.completions.async_create(
        model="gpt-4o",
        messages=[
            {
                "role": "user",
                "content": "Say this is a test"
            }
        ],
        stream=True,
    )
    
    async for chunk in stream:
        if chunk.choices[0].delta.content:
            print(chunk.choices[0].delta.content, end="")

asyncio.run(main())
```

_These examples use the new client implementation which properly handles streaming._

**_Also, make sure you're using the latest version of the library, as the streaming implementation has been improved in recent updates._**

**Comment by mazinn444** [comment]
Thanks, bro. I was trying the previous method. One question, the stream system sometimes bugs, is this normal? Another question, what is the fastest gpt4 provider?

**Comment by kqlio67** [comment]
Hi @mazinn444,

Thanks for bringing this up! You're absolutely right that streaming systems can occasionally experience issues. It's a common occurrence due to various factors like network instability, server load, or API limitations.

**To help minimize these issues, I've got a few suggestions:**
1. Implement proper error handling
2. Add retry logic for failed requests
3. Consider using timeouts to prevent hanging
4. Monitor your connection stability

I wrote a simple script for testing providers with GPT-4 that you might find useful. It can help you run your own benchmarks. **Here's the code:**.
```python
import asyncio
import time
from g4f.client import Client

async def test_provider(provider_name, model_name, timeout=30):
    client = Client(provider=provider_name)
    start_time = time.time()
    
    try:
        stream = await asyncio.wait_for(client.chat.completions.async_create(
            model=model_name,
            messages=[
                {
                    "role": "user",
                    "content": "Say this is a test"
                }
            ],
            stream=True,
        ), timeout=timeout)
        
        async for chunk in stream:
            if chunk.choices[0].delta.content:
                print(chunk.choices[0].delta.content, end="")
        
        end_time = time.time()
        return end_time - start_time
    except asyncio.TimeoutError:
        print(f"Timeout for provider {provider_name} with model {model_name}")
        return None
    except Exception as e:
        print(f"Error with provider {provider_name}: {e}")
        return None

async def main():
    providers_models = {
        "gpt-4o": ["NexraChatGPT4o", "Blackbox", "ChatGptEs", "DarkAI", "Liaobots", "Airforce"],
        "gpt-4o-mini": ["DDG", "ChatGptEs", "Pizzagpt", "RubiksAI", "Airforce", "ChatgptFree", "Koala", "ChatGpt"],
        "gpt-4-turbo": ["Airforce"],
        "gpt-4": ["Ai4Chat", "NexraBing", "NexraChatGptV2", "Airforce"]
    }
    
    for model, providers in providers_models.items():
        for provider in providers:
            response_time = await test_provider(provider, model)
            if response_time is not None:
                print(f"Response time for {provider} with model {model}: {response_time:.2f} seconds")

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("Program interrupted by user.")

```
**I ran tests both on my own server and a local machine. Here are the results from my server:**
**Server Results:**
```
Working Providers and Their Response Times:
    gpt-4o:
        NexraChatGPT4o: 4.13 seconds
        Blackbox: 0.90 seconds
        ChatGptEs: 1.57 seconds
        DarkAI: 2.31 seconds
        Liaobots: 1.70 seconds
        Airforce: 1.77 seconds

    gpt-4o-mini:
        DDG: 0.90 seconds
        ChatGptEs: 1.43 seconds
        Pizzagpt: 0.84 seconds
        RubiksAI: 3.40 seconds
        Airforce: 2.75 seconds
        ChatgptFree: 1.67 seconds
        Koala: 1.74 seconds
        ChatGpt: 2.95 seconds

    gpt-4-turbo:
        Airforce: 2.63 seconds

    gpt-4:
        Ai4Chat: 0.53 seconds
        NexraBing: 6.86 seconds
        NexraChatGptV2: 1.48 seconds
        Airforce: 2.05 seconds
```

I also ran tests on a local machine, but I'll skip those results for brevity. The local results showed some variations due to different network conditions and potential geographical factors.

**Based on these server results, the fastest providers for each model were:**
- `gpt-4`: Ai4Chat
- `gpt-4o`: Blackbox
- `gpt-4o-mini`: Pizzagpt
- `gpt-4-turbo`: Airforce (only provider available)

Keep in mind that these results can vary based on your location, network conditions, and server load. I'd recommend running the test script yourself to find the best provider for your specific use case.
