### ISSUE TITLE
OpenaiChat Provider New bug after update

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2455]
**Bug description**
I launch gpt-4o generation from the OpenaiChat provider, long loading and then an error.

**Request Post Url**
/v1/chat/completions

**Request Body**
```json
{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "provider": "OpenaiChat",
  "stream": true
}
```

**Bug Error**
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

**Comment by hlohaus** [comment]
Please authenticate using a HAR file; refer to the README for instructions.

**Comment by The2Alert** [comment]
HAR file exists and worked in previous versions:
![Screenshot 2024-12-05 104611](https://github.com/user-attachments/assets/322b5dd3-760e-47db-a077-8fcfc39d8ea0)

```yaml
version: '3.8'

services:
  g4f:
      image: hlohaus789/g4f:latest
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:1337:1337
        - 127.0.0.1:7900:7900
      shm_size: '2g'
      volumes:
        - ./har_and_cookies:/app/har_and_cookies
      restart: always
```
