### ISSUE TITLE
Proxy not working (OpenaiAccount/OpenaiChat Provider) (Docker image, Version: 0.3.9.7)

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2507]
**Screenshot**

![Screenshot 2024-12-25 132934](https://github.com/user-attachments/assets/01daa290-9c38-4ddd-8004-a8982f795f6f)

**Comment by The2Alert** [comment]
The **HAR file** was created according to the instructions in the README.

**Comment by The2Alert** [comment]
**docker-compose.yml**

```yml
version: '3.8'

services:
  g4f:
      image: hlohaus789/g4f:0.3.9.7
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:1337:1337
        - 127.0.0.1:7900:7900
      shm_size: '2g'
      volumes:
        - ./har_and_cookies:/app/har_and_cookies
      environment:
        G4F_PROXY: socks5://<SECRET>:<SECRET>@<SECRET>:<SECRET>
      restart: always
```
